<?php
/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */
//class JFormFieldCities extends JFormField{

class JFormFieldCities extends JFormFieldList{
	protected function getOptions()
	{
		$options =  parent::getOptions(); // TODO: Change the autogenerated stub
		$options[] = JHtmlSelect::options('123','foo');
		return $options;



		//$doc = JFactory::getDocument();
		//$doc->addScript();
		//$doc->addScriptDeclaration();
	}



}